title: Jellyfin Docs
description: Setup instructions and helpful hints for Jellyfin users.
theme: just-the-docs

url: https://docs.guettlerlabs.com

footer_content: "Favicon from <a href=\"https://icons8.com\">icons8</a>"
